# ~/.config/starship.toml

# --- GLOBAL SETTINGS ---
palette = "techdev"
add_newline = true 

# --- PALETTE DEFINITION ---
[palettes.techdev]
blue = "#82aaff"
purple = "#c792ea"
teal = "#89ddff"
green = "#c3e88d"
red = "#ff5370"
yellow = "#ffcb6b"
grey = "#545a68"

# --- PROMPT LAYOUT ---

# Left side of the prompt
format = """
$os\
$directory\
$fill\
$git_branch\
$git_status\
$cmd_duration\
$time\
"""


# Right side of the prompt

# --- MODULE CONFIGURATION ---

[os]
disabled = false
style = "bold fg:teal"
format = "[$symbol]($style)"

[os.symbols]
Linux = "Mint "

[directory]
style = "bold fg:blue"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "fg:red"
read_only = " "
format = "in [$path]($style)[$read_only]($read_only_style) "

[fill]
symbol = '.'

[git_branch]
symbol = ""
style = "bold fg:purple"
format = "on [$symbol $branch]($style) "

[git_status]
style = "bold fg:yellow"
format = "([$all_status$ahead_behind]($style)) "
conflicted = "⚔"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
stashed = ""
modified = ""
staged = '[](fg:green)'
renamed = "»"
deleted = "✘"

[cmd_duration]
min_time = 500
style = "bold fg:grey"
format = "took [$duration]($style) "

[time]
disabled = false
style = "bold fg:grey"
format = "at [$time]($style) "
time_format = "%T"

# The character module creates the newline before the prompt symbol
[character]
success_symbol = "[❯](bold fg:green)"
error_symbol = "[❯](bold fg:red)"
format = "$symbol "
